# Project: SobrecargaImprimir
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../../../../../../../sobrecargaOpImp/main.o ../../../../../../../sobrecargaOpImp/impDatoOperador.o
LINKOBJ  = ../../../../../../../sobrecargaOpImp/main.o ../../../../../../../sobrecargaOpImp/impDatoOperador.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = SobrecargaImprimir.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../../../../../../../sobrecargaOpImp/main.o: ../../../../../../../sobrecargaOpImp/main.cpp
	$(CPP) -c ../../../../../../../sobrecargaOpImp/main.cpp -o ../../../../../../../sobrecargaOpImp/main.o $(CXXFLAGS)

../../../../../../../sobrecargaOpImp/impDatoOperador.o: ../../../../../../../sobrecargaOpImp/impDatoOperador.cpp
	$(CPP) -c ../../../../../../../sobrecargaOpImp/impDatoOperador.cpp -o ../../../../../../../sobrecargaOpImp/impDatoOperador.o $(CXXFLAGS)
